CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "PasswordEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PasswordType" integer NOT NULL,
    "Password" text NOT NULL,
    "PasswordFor" text NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PasswordEntries" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_PasswordEntries_PasswordType_PasswordFor" ON "PasswordEntries" ("PasswordType", "PasswordFor");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240712113934_0_Initial', '7.0.20');

COMMIT;

